name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd luhn-brute && cargo build --verbose
    - name: Run tests
      run: cd luhn-brute && cargo test --verbose
    - name: Validate code format
      run: cd luhn-brute && cargo fmt --check
